linkPrefix = "/DomusCoins-SmartContract"
name = "doxity-simpleton"
version = "1.0.0"
description = "Solidity Documentation"
buildTime = 2018-02-19T15:26:21.036Z
target = "doxity"
src = "contracts/*"
dir = "pages/docs"
out = "docs"
author = "Ryan Hendricks"
homepage = "https://ryanhendricks.github.io/doxity-simpleton/"

[interaction]